config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'stores#index'
  resources :status, only: [:index]
  mount Sidekiq::Web => '/sidekiq'
  
  namespace :api, :defaults => { :format => 'json' }  do
    namespace :v1 do
      resource :monthly, only: [:show]
      resource :state, only: [:show]
      resource :abc_curve, only: [:show]
      resource :sku_curve, only: [:show]
      resource :source, only: [:show]
    end
  end
  resources :stores

  resource :sales do
    member do
      get "monthly"
      get 'weekly'
      get 'daily'
    end
  end

  resource :states do
    member do
      get "monthly"
      get 'weekly'
      get 'daily'
    end
  end

  resource :abc_curve do
    member do
      get "monthly"
      get 'weekly'
      get 'daily'
    end
  end

  resource :sku_curve do
    member do
      get "monthly"
      get 'weekly'
      get 'daily'
    end
  end

  resource :source do
    member do
      get "monthly"
      get 'weekly'
      get 'daily'
    end
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-static-top navbar-inverse">
  <div class="container-fluid">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="navbar-header">
      <%= link_to 'vnda-inteligence', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if params[:controller] == 'stores' %>">
          <%= link_to 'Lojas', stores_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inteligence</title>
  <%= stylesheet_link_tag '//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css' %>
  <%= javascript_include_tag '//code.jquery.com/jquery-2.1.1.min.js',
                             '//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>

  <div class="container-fluid">
    <%= render 'shared/flash_messages' %>
    <%= yield %>
  </div>
  <script type="text/javascript">
  $(function () {
    $('[data-toggle=tooltip]').tooltip();
  });
  </script>
</body>
</html>

app/views/layouts/insights.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title><%= @store.name %></title>
  
  <link rel="stylesheet" href="//inteligence-vnda.herokuapp.com/libs/assets/animate.css/animate.css" type="text/css" />
  <link rel="stylesheet" href="//inteligence-vnda.herokuapp.com/libs/assets/font-awesome/css/font-awesome.css" type="text/css" />
  <link rel="stylesheet" href="//inteligence-vnda.herokuapp.com/libs/jquery/bootstrap/dist/css/bootstrap.css" type="text/css" />
  <link rel="stylesheet" href="//inteligence-vnda.herokuapp.com/libs/jquery/waves/dist/waves.css" type="text/css" />

  <link rel="stylesheet" href="//inteligence-vnda.herokuapp.com/styles/material-design-icons.css" type="text/css" />
  <link rel="stylesheet" href="//inteligence-vnda.herokuapp.com/styles/font.css" type="text/css" />
  <link rel="stylesheet" href="//inteligence-vnda.herokuapp.com/styles/app.css" type="text/css" />
  <%= stylesheet_link_tag '//cdn.datatables.net/plug-ins/1.10.7/integration/bootstrap/3/dataTables.bootstrap.css' %>
  <style type="text/css">
    .dataTables_info{
      padding-bottom: 10px;  
    }
  </style>

</head>
<body>
<div class="app">
  
  <!-- aside -->
  <aside id="aside" class="app-aside modal fade " role="menu">
    <div class="left">
      <div class="box bg-white">
  <div class="navbar md-whiteframe-z1 no-radius blue">
    <!-- brand -->
    <a class="navbar-brand" style="background-color: #F57C00;">
      <span class="hidden-folded m-l inline"><%= @store.name %></span>
    </a>
    <!-- / brand -->
  </div>
  <div class="box-row">
    <div class="box-cell scrollable hover">
      <div class="box-inner">
        <div id="nav">
          <nav ui-nav>
            <ul class="nav">
              <li class="nav-header m-v-sm hidden-folded">
                Relatórios
              </li>
              <li class="b-b b m-v-sm"></li>
              <li>
                <a href="/admin/insights/sales/daily?token=<%= @store.token %>">
                  <i class="fa fa-calendar"></i>
                  <span>Vendas por Data</span>
                </a>
              </li>
              <li>
                <a href="/admin/insights/states/daily?token=<%= @store.token %>">
                  <i class="fa fa-location-arrow"></i>
                  <span>Vendas por Estado</span>
                </a>
              </li>
              <li>
                <a href="/admin/insights/abc_curve/daily?token=<%= @store.token %>">
                  <i class="fa fa-barcode"></i>
                  <span>Vendas por Produtos</span>
                </a>
              </li>
              <li>
                <a href="/admin/insights/sku_curve/daily?token=<%= @store.token %>">
                  <i class="fa fa-newspaper-o"></i>
                  <span>Vendas por Variante</span>
                </a>
              </li>
              <li>
                <a href="/admin/insights/source/daily?token=<%= @store.token %>">
                  <i class="fa fa-road"></i>
                  <span>Vendas por origem</span>
                </a>
              </li>
              <!--li>
                <a href="/state/daily?token=<%= @store.token %>"
                  <span>Vendas por estado</span>
                </a>
              </li>
              <li class="m-b-sm">
                <a href="/abc_curve/daily?token=<%= @store.token %>"
                  <span>Curva abc de produtos</span>
                </a>
              </li -->
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

    </div>
  </aside>
  <!-- / aside -->
  
  <!-- content -->
  <div id="content" class="app-content" role="main">
    <div class="box">
      <div class="navbar md-whiteframe-z1 no-radius" style="background-color: #F57C00;">
        <a md-ink-ripple  data-toggle="modal" data-target="#aside" class="navbar-item pull-left visible-xs visible-sm"><i class="mdi-navigation-menu i-24"></i></a>

        <div class="navbar-item pull-left h4" style="color: white;">Insights</div>
        
        <div class="pull-right"></div>

      </div>
      <div class="box-row">
        <div class="box-cell">
          <div class="box-inner padding">
            


  <div class="row">
    <div class="col-sm-12">
      <%= yield %>
    </div>
  </div>



          </div>
        </div>
      </div>
      <!-- / -->
    </div>

  </div>
  <!-- / content -->


    </div>
  </div>

    </div>
  </div>


</div>

<script src="//inteligence-vnda.herokuapp.com/libs/jquery/jquery/dist/jquery.js"></script>
<script src="//inteligence-vnda.herokuapp.com/libs/jquery/bootstrap/dist/js/bootstrap.js"></script>
<script src="//inteligence-vnda.herokuapp.com/libs/jquery/waves/dist/waves.js"></script>

<script src="//inteligence-vnda.herokuapp.com/scripts/ui-load.js"></script>
<script src="//inteligence-vnda.herokuapp.com/scripts/ui-jp.config.js"></script>
<script src="//inteligence-vnda.herokuapp.com/scripts/ui-jp.js"></script>
<script src="//inteligence-vnda.herokuapp.com/scripts/ui-nav.js"></script>
<script src="//inteligence-vnda.herokuapp.com/scripts/ui-toggle.js"></script>
<script src="//inteligence-vnda.herokuapp.com/scripts/ui-waves.js"></script>
<%= javascript_include_tag '//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js', '//cdn.datatables.net/plug-ins/1.10.7/integration/bootstrap/3/dataTables.bootstrap.js', '//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js', '//cdn.datatables.net/plug-ins/1.10.7/sorting/datetime-moment.js' %>
<script src="//inteligence-vnda.herokuapp.com/scripts/bootstrap-datepicker.js"></script>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $.fn.dataTable.moment( 'DD/MM/YYYY' );
    $.fn.dataTable.moment( 'MM/YYYY' );

    $('.datatables').dataTable({
      "bPaginate": false,
      "order": [[ 0, "desc" ]]
    });
    $.fn.datepicker.dates['pt-BR'] = {
      days: ["Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"],
      daysShort: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
      daysMin: ["Do", "Se", "Te", "Qu", "Qu", "Se", "Sa"],
      months: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"],
      monthsShort: ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"],
      today: "Hoje",
      clear: "Limpar"
    };
    $('.datepicker').datepicker({
      orientation: "auto top",
      language: "pt-BR"
    });

    $('#other_periods').submit(function(e){
      $('#success').hide();
      $('#error').hide();

      $.ajax({
        type: "GET",
        url: $('#other_periods').attr('action'),
        data: $("#other_periods").serialize(), // serializes the form's elements.
        success: function(data){
          $('#success').show();
        },
        error: function(data){
          $('#error').show();
        }
      });
      return false;   
    });
  });
</script>
</body>
</html>